# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Livepeer
  module Shared

    class Encryption < Livepeer::Utils::FieldAugmented
      extend T::Sig

      # Encryption key used to encrypt the asset. Only writable in the upload asset endpoints and cannot be retrieved back.
      field :encrypted_key, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('encryptedKey') } }


      sig { params(encrypted_key: String).void }
      def initialize(encrypted_key: nil)
        @encrypted_key = encrypted_key
      end
    end
  end
end
