# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Livepeer
  module Shared

    class IpfsFileInfo < Livepeer::Utils::FieldAugmented
      extend T::Sig

      # CID of the file on IPFS
      field :cid, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('cid') } }
      # URL to access file via HTTP through an IPFS gateway
      field :gateway_url, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('gatewayUrl') } }
      # URL with IPFS scheme for the file
      field :url, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('url') } }


      sig { params(cid: String, gateway_url: T.nilable(String), url: T.nilable(String)).void }
      def initialize(cid: nil, gateway_url: nil, url: nil)
        @cid = cid
        @gateway_url = gateway_url
        @url = url
      end
    end
  end
end
