# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Livepeer
  module Shared

    class IpfsExportParams < Livepeer::Utils::FieldAugmented
      extend T::Sig


      field :dollar_ref, T.nilable(Object), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('$ref') } }
      # Custom credentials for the Piñata service. Must have either
      # a JWT or an API key and an API secret.
      # 
      field :pinata, T.nilable(Object), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('pinata') } }


      sig { params(dollar_ref: T.nilable(Object), pinata: T.nilable(Object)).void }
      def initialize(dollar_ref: nil, pinata: nil)
        @dollar_ref = dollar_ref
        @pinata = pinata
      end
    end
  end
end
