# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Livepeer
  module Shared

    class Multistream < Livepeer::Utils::FieldAugmented
      extend T::Sig

      # References to targets where this stream will be simultaneously
      # streamed to
      # 
      field :targets, T.nilable(T::Array[Shared::Target]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('targets') } }


      sig { params(targets: T.nilable(T::Array[Shared::Target])).void }
      def initialize(targets: nil)
        @targets = targets
      end
    end
  end
end
