# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Livepeer
  module Shared
    # NftMetadataTemplate - Name of the NFT metadata template to export. 'player'
    # will embed the Livepeer Player on the NFT while 'file'
    # will reference only the immutable MP4 files.
    # 
    class NftMetadataTemplate < T::Enum
      enums do
        FILE = new('file')
        PLAYER = new('player')
      end
    end

  end
end
