# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Livepeer
  module Shared
    # Additional data to add to the NFT metadata exported to
    # IPFS. Will be deep merged with the default metadata
    # exported.
    # 
    class NftMetadata < Livepeer::Utils::FieldAugmented
      extend T::Sig



      
      def initialize; end
    end
  end
end
