# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Livepeer
  module Shared

    class Storage < Livepeer::Utils::FieldAugmented
      extend T::Sig

      # Set to true to make default export to IPFS. To customize the
      # pinned files, specify an object with a spec field. False or null
      # means to unpin from IPFS, but it's unsupported right now.
      # 
      field :ipfs, T.nilable(Object), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('ipfs') } }


      sig { params(ipfs: T.nilable(Object)).void }
      def initialize(ipfs: nil)
        @ipfs = ipfs
      end
    end
  end
end
