# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/multistream_target'

module Livepeer
  module Operations

    class GetMultistreamTargetRequest < Livepeer::Utils::FieldAugmented
      extend T::Sig

      # ID of the multistream target
      field :id, String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }


      sig { params(id: String).void }
      def initialize(id: nil)
        @id = id
      end
    end


    class GetMultistreamTargetResponse < Livepeer::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, String
      # HTTP response status code for this operation
      field :status_code, Integer
      # Success
      field :multistream_target, T.nilable(Shared::MultistreamTarget)
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, T.nilable(Faraday::Response)


      sig { params(content_type: String, status_code: Integer, multistream_target: T.nilable(Shared::MultistreamTarget), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, multistream_target: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @multistream_target = multistream_target
        @raw_response = raw_response
      end
    end
  end
end
