# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/asset'

module Livepeer
  module Operations

    class Task < Livepeer::Utils::FieldAugmented
      extend T::Sig


      field :id, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('id') } }


      sig { params(id: T.nilable(String)).void }
      def initialize(id: nil)
        @id = id
      end
    end

    # Success
    class RequestUploadResponseBody < Livepeer::Utils::FieldAugmented
      extend T::Sig


      field :asset, Shared::Asset, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('asset') } }

      field :task, Operations::Task, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('task') } }

      field :tus_endpoint, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('tusEndpoint') } }

      field :url, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('url') } }


      sig { params(asset: Shared::Asset, task: Operations::Task, tus_endpoint: String, url: String).void }
      def initialize(asset: nil, task: nil, tus_endpoint: nil, url: nil)
        @asset = asset
        @task = task
        @tus_endpoint = tus_endpoint
        @url = url
      end
    end


    class RequestUploadResponse < Livepeer::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, String
      # HTTP response status code for this operation
      field :status_code, Integer
      # Success
      field :object, T.nilable(Operations::RequestUploadResponseBody)
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, T.nilable(Faraday::Response)


      sig { params(content_type: String, status_code: Integer, object: T.nilable(Operations::RequestUploadResponseBody), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, object: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @object = object
        @raw_response = raw_response
      end
    end
  end
end
