# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/multistream_target_patch_payload'

module Livepeer
  module Operations

    class UpdateMultistreamTargetRequest < Livepeer::Utils::FieldAugmented
      extend T::Sig

      # ID of the multistream target
      field :id, String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

      field :multistream_target_patch_payload, Shared::MultistreamTargetPatchPayload, { 'request': { 'media_type': 'application/json' } }


      sig { params(id: String, multistream_target_patch_payload: Shared::MultistreamTargetPatchPayload).void }
      def initialize(id: nil, multistream_target_patch_payload: nil)
        @id = id
        @multistream_target_patch_payload = multistream_target_patch_payload
      end
    end


    class UpdateMultistreamTargetResponse < Livepeer::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, String
      # HTTP response status code for this operation
      field :status_code, Integer
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, T.nilable(Faraday::Response)


      sig { params(content_type: String, status_code: Integer, raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @raw_response = raw_response
      end
    end
  end
end
